# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analise.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analise.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranalise.proto\x12\x07\x61nalise\"0\n\x0b\x44\x61\x64osSensor\x12\x0c\n\x04sala\x18\x01 \x01(\t\x12\x13\n\x0btemperatura\x18\x02 \x01(\x02\"<\n\x10ResultadoAnalise\x12\x0e\n\x06\x61lerta\x18\x01 \x01(\t\x12\x18\n\x10\x61\x63\x61o_recomendada\x18\x02 \x01(\x08\x32X\n\x0eServicoAnalise\x12\x46\n\x13\x41nalisarTemperatura\x12\x14.analise.DadosSensor\x1a\x19.analise.ResultadoAnaliseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analise_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DADOSSENSOR']._serialized_start=26
  _globals['_DADOSSENSOR']._serialized_end=74
  _globals['_RESULTADOANALISE']._serialized_start=76
  _globals['_RESULTADOANALISE']._serialized_end=136
  _globals['_SERVICOANALISE']._serialized_start=138
  _globals['_SERVICOANALISE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
